# Generated by Django 5.2 on 2025-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.IntegerField(choices=[(0, 'init'), (1, 'in_progress'), (2, 'finished')], default=0),
        ),
    ]
